# adapted from radvel .travis.yml file

language: python
sudo: False

cache:
   directories:
     - $HOME/download
     - $HOME/miniconda2
     - $HOME/miniconda3

python:
  - "2.7"
  - "3.6"

before_install:
    - export py="$(echo $TRAVIS_PYTHON_VERSION | head -c 1)"
    - wget http://repo.continuum.io/miniconda/Miniconda${py}-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - bash miniconda.sh -b -u -p $HOME/miniconda
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm

install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy cython gcc
    - pip install pytest pytest-cov coverage coveralls
    - pip install . --upgrade
    - CXX=g++ python setup.py build_ext -i

# configure a headless display using xvbf to test plot generation
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 2 # give xvfb some time to start

# run tests in Travis-CI virtual env
script:
     - py.test --cov-report= --cov=orbitize tests/

after_success:
    - coveralls
